version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kheruvimovy2-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN=kheruvimovy.ru
    # Добавьте переменные окружения (.env), если они нужны вашему бэкенду
    # env_file:
    #   - .env
