<?php
/**
 * Modern Wedding CMD - WordPress/Joomla style Web Installer Wizard
 * Beautiful, reliable 1-click installer which connects to MySQL,
 * initializes database tables, populates default templates, and saves config.php.
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$lockFile = __DIR__ . '/install.lock';
$configFile = __DIR__ . '/config.php';
$schemaFile = __DIR__ . '/schema.sql';

// Prevent re-installation if a lock file exists
$alreadyInstalled = false;
if (file_exists($lockFile)) {
    $alreadyInstalled = true;
}

// Check requirements
$requirements = [
    'php_version' => [
        'title' => 'Версия PHP >= 8.0',
        'passed' => version_compare(PHP_VERSION, '8.0.0', '>='),
        'message' => 'Текущая версия: ' . PHP_VERSION
    ],
    'pdo_mysql' => [
        'title' => 'Расширение PDO MySQL',
        'passed' => extension_loaded('pdo_mysql'),
        'message' => extension_loaded('pdo_mysql') ? 'Доступно' : 'Отсутствует в вашей системе PHP'
    ],
    'config_writable' => [
        'title' => 'Запись в каталог / Доступ к config.php',
        'passed' => is_writable(__DIR__) || (file_exists($configFile) && is_writable($configFile)),
        'message' => is_writable(__DIR__) ? 'Разрешено' : 'Проверьте права на запись в папку'
    ],
    'schema_exists' => [
        'title' => 'Файл схемы СУБД (schema.sql)',
        'passed' => file_exists($schemaFile),
        'message' => file_exists($schemaFile) ? 'Найден' : 'Файл schema.sql отсутствует в каталоге'
    ]
];

$allPassed = true;
foreach ($requirements as $req) {
    if (!$req['passed']) {
        $allPassed = false;
    }
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
if ($alreadyInstalled) {
    $step = 'locked';
}

$errorMsg = '';
$successMsg = '';

// Handle DB Connection & Script Execution
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2 && !$alreadyInstalled) {
    $db_host = trim($_POST['db_host'] ?? 'localhost');
    $db_port = trim($_POST['db_port'] ?? '3306');
    $db_name = trim($_POST['db_name'] ?? 'kheruvimovy_wedding');
    $db_user = trim($_POST['db_user'] ?? 'root');
    $db_pass = $_POST['db_pass'] ?? '';
    
    try {
        // Step A: Attempt connection without database first to see if we can connect to MySQL
        $dsnWithoutDb = sprintf('mysql:host=%s;port=%s;charset=utf8mb4', $db_host, $db_port);
        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
        ];
        
        $pdo = new PDO($dsnWithoutDb, $db_user, $db_pass, $options);
        
        // Step B: Ensure the database exists or create it
        // We will execute a query to create the database if permitted
        $pdo->exec(sprintf("CREATE DATABASE IF NOT EXISTS `%s` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci", $db_name));
        
        // Connect to the specific database
        $pdo->exec(sprintf("USE `%s`", $db_name));
        
        // Step C: Import Schema SQL
        if (file_exists($schemaFile)) {
            $sqlContent = file_get_contents($schemaFile);
            
            // Clean SQL commands to run cleanly one by one (multi-queries in single execute can have issues depending on PDO drivers)
            // Remove MySQL Comments
            $sqlContent = preg_replace('/^\s*--.*$/m', '', $sqlContent);
            $sqlContent = preg_replace('/^\s*#.*$/m', '', $sqlContent);
            
            // Split database commands by semicolon
            $queries = explode(';', $sqlContent);
            
            // Execute each SQL command individually inside a transaction
            $pdo->beginTransaction();
            foreach ($queries as $query) {
                $query = trim($query);
                if (!empty($query)) {
                    // Skip general DB-level commands in case they enforce specific local server state
                    if (stripos($query, 'CREATE DATABASE') === 0 || stripos($query, 'USE ') === 0) {
                        continue;
                    }
                    $pdo->exec($query);
                }
            }
            $pdo->commit();
        } else {
            throw new Exception("Файл schema.sql не найден для выполнения импорта таблиц.");
        }
        
        // Step D: Write new values to config.php
        $configContent = "<?php
/**
 * Modern Wedding CMS - Database Configuration (Auto-Generated by Web Installer)
 * Uses PHP Data Objects (PDO) for safe prepared queries & transaction control.
 */

define('DB_HOST', '" . addslashes($db_host) . "');
define('DB_PORT', '" . addslashes($db_port) . "');
define('DB_NAME', '" . addslashes($db_name) . "');
define('DB_USER', '" . addslashes($db_user) . "');
define('DB_PASS', '" . addslashes($db_pass) . "');

function getDatabaseConnection(): PDO {
    static \$connection = null;
    
    if (\$connection === null) {
        \$dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4', DB_HOST, DB_PORT, DB_NAME);
        
        \$options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
            PDO::MYSQL_ATTR_INIT_COMMAND => \"SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci\"
        ];
        
        try {
            \$connection = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
        } catch (PDOException \$e) {
            http_response_code(500);
            echo json_encode([
                'success' => false,
                'error' => 'Database connection failed. Please verify credentials in config.php',
                'details' => \$e->getMessage()
            ]);
            exit;
        }
    }
    
    return \$connection;
}
";
        if (file_put_contents($configFile, $configContent) === false) {
            throw new Exception("Не удалось обновить содержимое config.php. Пожалуйста, предоставьте права записи.");
        }
        
        // Step E: Set Lock File to avoid overwrites
        file_put_contents($lockFile, "Installed on " . date('Y-m-d H:i:s') . "\n");
        
        // Proceed to Step 3 - Success Screen!
        $step = 3;
    } catch (Exception $e) {
        if (isset($pdo) && $pdo->inTransaction()) {
            $pdo->rollBack();
        }
        $errorMsg = "Ошибка при установке системы: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Установка Свадебного Веб-сайта — Мастер конфигурации</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300&family=Inter:wght@300;400;500;600&display=swap" rel="stylesheet">
    <!-- Tailwind CSS (Direct CDN) -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'ivory': '#fdfbf7',
                        'beige-bg': '#f5f1e8',
                        'imperial': '#c5a880',
                        'imperial-dark': '#b3956d',
                        'estate': '#1c1917',
                    },
                    fontFamily: {
                        'display': ['"Cormorant Garamond"', 'serif'],
                        'sans': ['"Inter"', 'sans-serif'],
                    }
                }
            }
        }
    </script>
    <style>
        body {
            background-color: #fdfbf7;
            color: #1c1917;
        }
        .vintage-border {
            border: 1px solid rgba(197, 168, 128, 0.3);
        }
        .gold-glow {
            box-shadow: 0 10px 30px -10px rgba(197, 168, 128, 0.2);
        }
    </style>
</head>
<body class="min-h-screen py-16 px-4 flex items-center justify-center font-sans tracking-wide">

    <div class="w-full max-w-xl bg-ivory rounded shadow-2xl relative border border-imperial/10 p-8 md:p-12 gold-glow">
        <!-- Corner ornaments to match the premium theme -->
        <div class="absolute top-2 left-2 w-8 h-8 border-t border-l border-imperial/30"></div>
        <div class="absolute top-2 right-2 w-8 h-8 border-t border-r border-imperial/30"></div>
        <div class="absolute bottom-2 left-2 w-8 h-8 border-b border-l border-imperial/30"></div>
        <div class="absolute bottom-2 right-2 w-8 h-8 border-b border-r border-imperial/30"></div>

        <div class="text-center mb-10">
            <h1 class="font-display italic text-4xl text-imperial font-medium mb-2">Усадьба Херувимовых</h1>
            <p class="text-[10px] uppercase tracking-[0.5em] text-stone-400 font-semibold mb-6">Мастер установки свадебной CMS</p>
            
            <div class="flex items-center justify-center gap-2">
                <span class="w-1.5 h-1.5 rounded-full <?php echo $step >= 1 ? 'bg-imperial' : 'bg-stone-200'; ?>"></span>
                <span class="w-12 h-px bg-imperial/20"></span>
                <span class="w-1.5 h-1.5 rounded-full <?php echo $step >= 2 ? 'bg-imperial' : 'bg-stone-200'; ?>"></span>
                <span class="w-12 h-px bg-imperial/20"></span>
                <span class="w-1.5 h-1.5 rounded-full <?php echo $step >= 3 ? 'bg-imperial' : 'bg-stone-200'; ?>"></span>
            </div>
        </div>

        <?php if ($errorMsg): ?>
            <div class="mb-8 p-4 bg-red-50 border border-red-200 rounded text-red-800 text-sm flex gap-3 items-start">
                <svg class="w-5 h-5 flex-shrink-0 text-red-600 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
                </svg>
                <span><?php echo htmlspecialchars($errorMsg); ?></span>
            </div>
        <?php endif; ?>

        <?php if ($step === 'locked'): ?>
            <div class="text-center py-6 space-y-6">
                <div class="w-16 h-16 rounded-full bg-imperial/10 border border-imperial/30 flex items-center justify-center mx-auto">
                    <svg class="h-6 w-6 text-imperial" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                    </svg>
                </div>
                <h3 class="font-display italic text-3xl font-light text-estate">Инсталляция заблокирована</h3>
                <p class="text-stone-500 leading-relaxed max-w-sm mx-auto text-sm font-light">
                    Система Wedding CMS уже успешно установлена. В целях безопасности возможность изменения параметров баз заблокирована.
                </p>
                <p class="text-[11px] text-stone-400 max-w-sm mx-auto uppercase tracking-wider bg-stone-50 p-3 border rounded">
                    Чтобы повторить установку, удалите файл <code class="font-mono bg-stone-100 text-red-600 px-1 py-0.5 rounded">install.lock</code> в каталоге PHP.
                </p>
                <div class="pt-6">
                    <a href="api.php?action=get_content" target="_blank" class="inline-block border border-imperial px-8 py-3 text-xs uppercase tracking-widest text-imperial font-semibold hover:bg-imperial hover:text-white transition-all cursor-pointer">
                        Проверить API
                    </a>
                </div>
            </div>

        <?php elseif ($step === 1): ?>
            <!-- STEP 1: Requirements check & Greetings -->
            <div class="space-y-8">
                <div class="space-y-4">
                    <h3 class="font-display italic text-2xl font-light text-estate text-center">Приветствуем васъ в усадьбе!</h3>
                    <p class="text-stone-500 font-light text-justify text-sm leading-relaxed">
                        Этот интуитивный мастер поможет вам развернуть свадебное приглашение на любом хостинге за считанные секунды. Автоматическая подготовка базы данных и тонкая конфигурация за один клик.
                    </p>
                </div>

                <div class="bg-stone-50 group border border-stone-100 p-6 rounded space-y-4">
                    <h4 class="text-[11px] font-bold uppercase tracking-widest text-imperial mb-2">Проверка окружения сервера</h4>
                    <div class="space-y-3">
                        <?php foreach ($requirements as $key => $req): ?>
                            <div class="flex items-center justify-between text-xs py-1 border-b border-stone-150 last:border-0">
                                <span class="text-stone-600 font-medium"><?php echo $req['title']; ?></span>
                                <div class="flex items-center gap-2">
                                    <span class="text-[10px] text-stone-400 italic"><?php echo $req['message']; ?></span>
                                    <?php if ($req['passed']): ?>
                                        <span class="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                                    <?php else: ?>
                                        <span class="w-2.5 h-2.5 rounded-full bg-red-500"></span>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="pt-4">
                    <?php if ($allPassed): ?>
                        <a href="?step=2" class="block w-full text-center border border-imperial bg-imperial text-white py-4 text-xs font-semibold uppercase tracking-widest hover:bg-imperial-dark transition-all cursor-pointer">
                            Начать установку
                        </a>
                    <?php else: ?>
                        <p class="text-red-600 text-xs text-center font-semibold mb-3">Внимание! Обнаружены ошибки совместимости. Разрешите права записи или обновите сервер PHP.</p>
                        <button disabled class="w-full opacity-50 bg-stone-100 border border-stone-200 text-stone-400 py-4 text-xs font-semibold uppercase tracking-widest cursor-not-allowed">
                            Установка заблокирована ошибками
                        </button>
                    <?php endif; ?>
                </div>
            </div>

        <?php elseif ($step === 2): ?>
            <!-- STEP 2: Database Configuration form -->
            <form method="POST" class="space-y-6">
                <div class="space-y-2 text-center mb-6">
                    <h3 class="font-display italic text-2xl font-light text-estate">Параметры соединения СУБД</h3>
                    <p class="text-stone-400 text-xs font-light">Пожалуйста, внесите реквизиты вашей базы данных MySQL</p>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div class="space-y-2 md:col-span-2">
                        <label class="text-[9px] uppercase tracking-[0.2em] text-stone-400 font-bold block">Хост базы данных (Database Host)</label>
                        <input required type="text" name="db_host" value="localhost" class="w-full bg-stone-50 border border-stone-250 p-3 rounded focus:outline-none focus:border-imperial transition-colors text-sm font-medium">
                    </div>
                    <div class="space-y-2">
                        <label class="text-[9px] uppercase tracking-[0.2em] text-stone-400 font-bold block">Порт СУБД</label>
                        <input required type="text" name="db_port" value="3306" class="w-full bg-stone-50 border border-stone-250 p-3 rounded focus:outline-none focus:border-imperial transition-colors text-sm font-medium">
                    </div>
                </div>

                <div class="space-y-2">
                    <label class="text-[9px] uppercase tracking-[0.2em] text-stone-400 font-bold block">Имя создаваемой базы данных</label>
                    <input required type="text" name="db_name" value="kheruvimovy_wedding" class="w-full bg-stone-50 border border-stone-250 p-3 rounded focus:outline-none focus:border-imperial transition-colors text-sm font-medium">
                    <p class="text-[10px] text-stone-400 italic">Будет автоматически создана при отсутствии на хостинг-сервере</p>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div class="space-y-2">
                        <label class="text-[9px] uppercase tracking-[0.2em] text-stone-400 font-bold block">Имя пользователя (User)</label>
                        <input required type="text" name="db_user" value="root" class="w-full bg-stone-50 border border-stone-250 p-3 rounded focus:outline-none focus:border-imperial transition-colors text-sm font-medium">
                    </div>
                    <div class="space-y-2">
                        <label class="text-[9px] uppercase tracking-[0.2em] text-stone-400 font-bold block">Пароль (Password)</label>
                        <input type="password" name="db_pass" placeholder="Если пароля нет, оставьте пустым" class="w-full bg-stone-50 border border-stone-250 p-3 rounded focus:outline-none focus:border-imperial transition-colors text-sm font-medium">
                    </div>
                </div>

                <div class="pt-6 flex gap-4">
                    <a href="?step=1" class="w-1/3 text-center border border-stone-200 text-stone-400 py-4 text-xs font-semibold uppercase tracking-widest hover:bg-stone-50 transition-all cursor-pointer">
                        Назад
                    </a>
                    <button type="submit" class="w-2/3 border border-imperial bg-imperial text-white py-4 text-xs font-semibold uppercase tracking-widest hover:bg-imperial-dark transition-all cursor-pointer">
                        Запустить инсталляцию
                    </button>
                </div>
            </form>

        <?php elseif ($step === 3): ?>
            <!-- STEP 3: Complete screen -->
            <div class="text-center py-6 space-y-8">
                <div class="w-16 h-16 rounded-full bg-emerald-50 border border-emerald-200 flex items-center justify-center mx-auto animate-bounce">
                    <svg class="h-6 w-6 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                    </svg>
                </div>
                
                <div class="space-y-3">
                    <h3 class="font-display italic text-3xl font-light text-estate">Установка завершена!</h3>
                    <p class="text-stone-500 font-light text-sm max-w-sm mx-auto leading-relaxed">
                        Поздравляем! База данных Wedding CMS успешно сконфигурирована, заполнена дефолтными благородными усадебными данными и готова принимать гостей.
                    </p>
                </div>

                <div class="bg-stone-50 p-6 rounded space-y-3 text-left border border-stone-100 max-w-md mx-auto">
                    <h4 class="text-[10px] font-bold uppercase tracking-widest text-imperial">Выполненные шаги:</h4>
                    <ul class="text-xs text-stone-600 space-y-2">
                        <li class="flex items-center gap-2">✓ Создана база данных в СУБД</li>
                        <li class="flex items-center gap-2">✓ Конфигурационный файл <code class="font-mono bg-stone-100 text-emerald-600 px-1 rounded">config.php</code> записан</li>
                        <li class="flex items-center gap-2">✓ Создан файл защиты <code class="font-mono bg-stone-100 text-stone-600 px-1 rounded">install.lock</code></li>
                        <li class="flex items-center gap-2">✓ Импортированы таблицы: <code class="font-mono text-stone-500">page_settings, schedule, estate_rules, rsvp_submissions</code></li>
                    </ul>
                </div>

                <div class="pt-6 flex flex-col sm:flex-row gap-4 justify-center">
                    <a href="api.php?action=get_content" target="_blank" class="border border-stone-200 px-8 py-3.5 text-xs uppercase tracking-widest text-stone-500 font-bold hover:bg-stone-50 transition-all cursor-pointer">
                        Открыть API бэкенда
                    </a>
                    <a href="/" class="border border-imperial bg-imperial px-8 py-3.5 text-xs uppercase tracking-widest text-white font-bold hover:bg-imperial-dark transition-all cursor-pointer">
                        Перейти к сайту
                    </a>
                </div>
            </div>
        <?php endif; ?>

    </div>

</body>
</html>
